FROM node:15.5.0-alpine

RUN mkdir -p /app
WORKDIR /app
COPY package.json .
RUN npm install --quiet
EXPOSE 8080
COPY . ./code

ENV PORT=5000
ENV HOST=0.0.0.0

ENV SZLIMIT=3
ENV NZLIMIT=2

CMD ["npm", "run", "start.dev"]
