version: "3.9"
services:
        web:
                build:
                        context: .
                        dockerfile: Dockerfile.dev
                ports:
                        - "5000:5000"
                volumes:
                        - .:/app/code
                depends_on:
                        - mongo
        mongo:
                image: mongo
                restart: always
                volumes:
                        - mongo-data:/data/db
volumes:
        mongo-data:
